### ISSUE TITLE
Harmonize POP and intensity

### ISSUE THREAD

**Issue by alexander0042** [Pirate-Weather/pirate-weather-code#30] opened 2024-12-03 21:07 UTC
Interesting- it technically shouldn't happen, but I'm not surprised that it does. What I suspect is happening comes from [this line in the ingest script](https://github.com/Pirate-Weather/pirate-weather-code/blob/53b2e6c85dfd9dab074dacb5e475632f02c59997/API/GEFS_Local_Ingest.py#L300), where it finds the number of ensembles where there's more than 1 mm of precipitation. So if a couple members have 0<x<0.1 mm of precipitation, then this could happen. 

The best fix is probably to reduce that POP ingest threshold to something closer to 0.05 mm (I picked 0.1 somewhat arbitrarily), as well as add a check in the response script to intensity to zero if POP == 0, probably in the [hourly calculation ](https://github.com/Pirate-Weather/pirate-weather-code/blob/e6f5c5712548d45ab8d9f6e556aa7dc46ca2e380/API/responseLocal.py#L2484) so that the situation doesn't occur where all the hourly blocks say 0 but there's a daily accumulation.

_Originally posted by @alexander0042 in https://github.com/Pirate-Weather/pirate-weather-code/issues/27#issuecomment-2515552773_

**Comment by cloneofghosts** [comment] 2024-12-04 17:32
@alexander0042 Just noticed this happen in the NBM domain. I also see snow intensities in the hour and daily block seem to be multiplied by 10 which I assume is you working on something?

```json
"summary": "Possible Flurries and Breezy",
"icon": "snow",
"precipIntensity": 0.0579,
"precipProbability": 0,
"precipIntensityError": 0.0263,
"precipAccumulation": 0.0058,
"precipType": "snow",
```

**Comment by alexander0042** [comment] 2024-12-04 17:48
Yea, I found a decently significant bug in that the snow intensities aren't being multiplied by the 10x factor, which in turn messes up the text calculations. So if 5 cm of snow is called for in an hour, using si units, `precipIntensity` should be 50 (in mm) and 'precipAccumulation' should be 5 (in cm)? Unless I'm crazy and we decided to report `precipIntensity` in either mm or cm depending on the type, in which case I need to update the docs as well as the text generation thresholds (which assume intensity is in mm)

**Comment by cloneofghosts** [comment] 2024-12-04 18:00
> Yea, I found a decently significant bug in that the snow intensities aren't being multiplied by the 10x factor, which in turn messes up the text calculations. So if 5 cm of snow is called for in an hour, using si units, `precipIntensity` should be 50 (in mm) and 'precipAccumulation' should be 5 (in cm)? 

Looking at an archive of the [DarkSky docs](https://web.archive.org/web/20200402135354/https://darksky.net/dev/docs) it lists `precipIntensity` is in mm/h so in this case it snow should be 50 mm for intensity and 5cm for accumulation.

The text calculations would need to change but its a fairly simple change as you'd just need to multiply it by 10. So it would become: 1.33, 8.33 and 33.33 for the snow thresholds. The currently and minutely blocks appear to be unchanged?

**Comment by alexander0042** [comment] 2024-12-04 18:09
I don't think they're adjusting by the snow:water ratios for the text thresholds, so 3.33 mm/ hour of snow would be heavy snow. This feels a little low in my opinion, but maybe coming from Ottawa we have an unrealistic threshold for heave snow?

**Comment by cloneofghosts** [comment] 2024-12-04 18:48
> I don't think they're adjusting by the snow:water ratios for the text thresholds, so 3.33 mm/ hour of snow would be heavy snow. This feels a little low in my opinion, but maybe coming from Ottawa we have an unrealistic threshold for heave snow?

You're probably right about them not considering the snow:water ratio. The current thresholds would make sense if they were in cm not mm (so Heavy Snow would be 3.33 cm/h). I see this currently on the dev server:

``json
"summary": "Heavy Snow and Breezy",
"icon": "snow",
"nearestStormDistance": 0,
"nearestStormBearing": 0,
"precipIntensity": 3.6001,
```

Taking a look outside the snow is more like Light Snow which would be the case if the text thresholds used cm/h instead of mm/h. Would this might mess up the thresholds in Imperial units and the text summaries at all? It may only affect the minutely ones if the `precipType` changes from snow to sleet or rain.

**Comment by cloneofghosts** [comment] 2024-12-04 19:14
> Ok, yea, that makes sense. A quick shows that snowfall rates of 5 cm/h happen from time to time, so I think that it makes sense to use that. Just made a commit that implements that, and hoping to push 2.5 to prod tomorrow to correct the snow intensity issue!

So V2.5 will include the translation module but not the summaries then? The individual day summaries still use the old icon/summary logic. For now you could pass the averaged daily values into the summary module until the summaries get setup. The minutely summary hasn't been setup either but I guess that will come in a future update?

The translation module on the dev server doesn't seem to be the most up-to-date as I've added the med/heavy possible text and started translating some of the languages. I would guess that the server needs to be restarted for it to be updated?

**Comment by alexander0042** [comment] 2024-12-04 19:31
Yea, that's a good idea! I'll try exactly that out for daily summaries as a 2.5 stopgap!

Sorry for missing your translations improvements! Because that library comes in as a node module, it needs a rebuilt docker image, so doesn't happen unless I regenerate it. Eventually I want them to move from AWS to GitHub for image generation, but for now this works well enough, so long as I remember to do it!

**Comment by cloneofghosts** [comment] 2024-12-04 19:41
> Yea, that's a good idea! I'll try exactly that out for daily summaries as a 2.5 stopgap!

You could do something similar for the minutely summaries for now until the text summaries get added (2.6 I'm assuming?). If no precipitation use the current icon/summary and if precipitation use the primary type and the medium precipitation text so medium-rain for rain.

> Sorry for missing your translations improvements! Because that library comes in as a node module, it needs a rebuilt docker image, so doesn't happen unless I regenerate it. Eventually I want them to move from AWS to GitHub for image generation, but for now this works well enough, so long as I remember to do it!

Considering we don't have translations for that text yet it's fine to not include them for now. I'll probably go tonight and translate mostly clear into the languages I haven't done yet. It likely won't be the best translation but better than it being in English.

**Comment by alexander0042** [comment] 2024-12-04 20:03
Even simpler, the way I've got it working now is to use average values for daily, and just the same as currently for minutely. It's an improvement to the current approach, but nice and straightforward to implement! 

I'll leave out the "possible-medium" and "possibly-heavy" text summaries for now, but it'll be easy to bring them live once all the text is in!

**Comment by cloneofghosts** [comment] 2024-12-04 20:15
> Even simpler, the way I've got it working now is to use average values for daily, and just the same as currently for minutely. It's an improvement to the current approach, but nice and straightforward to implement!
> 
> I'll leave out the "possible-medium" and "possibly-heavy" text summaries for now, but it'll be easy to bring them live once all the text is in!

Sounds good. Will work on adding translations for mostly clear so its at least translated and if its wrong then the community can contribute better translations. :smile:

**Comment by cloneofghosts** [comment] 2024-12-04 20:39
@alexander0042 Just thought of something: I'm assuming the daily summaries aren't using the current 1mm accumulation thresholds to show the rain/snow/sleet icon right? Not a huge deal if you aren't but we'll need to update the docs to clarify the changes.

**Comment by alexander0042** [comment] 2024-12-04 20:44
As it stands now, they're using the same factors as hourly averaged out over the day. So if a day has 24 mm of snow in the forecast, then it'll use 1 mm (24 mm/day / 24 hours/day) as the threshold

**Comment by cloneofghosts** [comment] 2024-12-04 20:50
> As it stands now, they're using the same factors as hourly averaged out over the day. So if a day has 24 mm of snow in the forecast, then it'll use 1 mm (24 mm/day / 24 hours/day) as the threshold. I think it makes more sense to stick with the existing limits we worked out though, so I'll change it before release!

So showing the precipitation text/summary is purely based on average intensity and it accumulation doesn't need to reach a certain threshold in order to show the icon?

**Comment by alexander0042** [comment] 2024-12-04 21:01
It's a really good point. The current code uses 0.02 mm as the icon threshold (same as v2.4), same threshold for snow/ rain. In v2.4, daily used total accumulation greater than 1 mm for rain and 10 mm for snow, which I think makes sense. I'll update the text/icon generation script to align with this approach. basically by adding a "daily" vs "hourly" flag, then editing [this line](https://github.com/Pirate-Weather/pirate-weather-code/blob/127a49a9a655de71238f629e2ead790584d258bd/API/PirateText.py#L85) accordingly.

**Comment by cloneofghosts** [comment] 2024-12-04 23:46
@alexander0042 Just FYI: I finished translating mostly clear in the remaining languages. Probably not the best translation but better than nothing.

**Comment by cloneofghosts** [comment] 2024-12-05 15:16
@alexander0042 Just have a couple of quick questions for you:

1. Is daily `precipIntensity` not forward looking like accumulation? The API isn't forecasting any more snow for the day but the intensity and max intensity are not zero like the accumulation is.

```json
"time": 1733374800,
"summary": "Possible Flurries",
"icon": "snow",
"sunriseTime": 1733401626,
"sunsetTime": 1733433614,
"moonPhase": 0.14,
"precipIntensity": 0.7409,
"precipIntensityMax": 2.5403,
"precipIntensityMaxTime": 1733374800,
"precipProbability": 0.15,
"precipAccumulation": 0,
"precipType": "snow",
"temperatureHigh": 1.1,
"temperatureHighTime": 1733418000,
"temperatureLow": -8.46,
"temperatureLowTime": 1733482800,
"apparentTemperatureHigh": -4.44,
"apparentTemperatureHighTime": 1733414400,
"apparentTemperatureLow": -16.78,
"apparentTemperatureLowTime": 1733479200,
"dewPoint": -2.96,
"humidity": 0.88,
"pressure": 998.06,
"windSpeed": 22.02,
"windGust": 35.65,
"windGustTime": 1733443200,
"windBearing": 244.58,
"cloudCover": 0.8,
"uvIndex": 2.09,
"uvIndexTime": 1733418000,
"visibility": 7.33,
"temperatureMin": -5.15,
"temperatureMinTime": 1733457600,
"temperatureMax": 1.1,
"temperatureMaxTime": 1733418000,
"apparentTemperatureMin": -14.31,
"apparentTemperatureMinTime": 1733457600,
"apparentTemperatureMax": -4.44,
"apparentTemperatureMaxTime": 1733414400
```

2. Is the daily `precipIntensity` not taking into account the snow liquid changes you made to the other blocks? Today's `precipIntensity` would be high enough for the summary to show Possible Light Snow but with the changes it only shows Possible Flurries

**Comment by alexander0042** [comment] 2024-12-05 16:09
Good catch- the reason they were different is that I zero out accumulation before the forecast request time, but wasn't doing that for intensity. I've corrected it to harmonize this, so daily intensity should always be the accumulation / 24 hours /10(cm to mm)

**Comment by cloneofghosts** [comment] 2024-12-05 16:36
> Good catch- the reason they were different is that I zero out accumulation before the forecast request time, but wasn't doing that for intensity. I've corrected it to harmonize this, so daily intensity should always be the accumulation / 24 hours /10(cm to mm)

Just to clarify the `precipIntensity` shown in the daily block for snow is the liquid equivalent right?

```json
"time": 1733893200,
"summary": "Flurries",
"icon": "snow",
"precipIntensity": 0.1856,
"precipIntensityMax": 0.5563,
```

This `precipIntensity` would have displayed Light Snow before but after the change to the summaries it shows Flurries. This is due to the change for the snow text summaries to use cm instead of mm (if the liquid equivalent is being used for daily).

**Comment by alexander0042** [comment] 2024-12-05 16:40
Nope, shouldn't ever show liquid equivalent- so in that example it's showing an average of 0.1856 mm/h of snow during the day, with a max rate of 0.5563 mm/h. The accumulation should show 0.1856 mm/h * 24h = 4.45 mm=**0.445 cm** (fingers crossed that's what it's showing)

I still need to fix the text summaries though, so I think that's where the problem is.

**Comment by cloneofghosts** [comment] 2024-12-05 16:42
> Nope, shouldn't ever show liquid equivalent- so in that example it's showing an average of 0.1856 mm/h of snow during the day, with a max rate of 0.5563 mm/h. The accumulation should show 0.1856 mm/h * 24h = 4.45 mm=**0.445 cm** (fingers crossed that's what it's showing)

Just double checked and it's showing this:

```json
"precipAccumulation": 0.44510000000000005,
```

For some reason the value isn't being rounded to four decimal points but checks out with what you said.

**Comment by alexander0042** [comment] 2024-12-05 16:50
Ok, that's good! Strange that accumulation is different on prod vs dev, since I haven't changed anything there? Can you check the snow/liquid/ice accumulations vs the general one?

**Comment by cloneofghosts** [comment] 2024-12-05 16:56
> Ok, that's good! Strange that accumulation is different on prod vs dev, since I haven't changed anything there? Can you check the snow/liquid/ice accumulations vs the general one?

Here you go:

Live:
```json
"time": 1733893200,
"icon": "partly-cloudy-day",
"summary": "Partly Cloudy",
"dawnTime": 1733918296,
"sunriseTime": 1733920370,
"sunsetTime": 1733951995,
"duskTime": 1733954068,
"moonPhase": 0.35,
"precipIntensity": 0.0848,
"precipIntensityMax": 0.184,
"precipIntensityMaxTime": 1733893200,
"precipProbability": 0.36,
"precipAccumulation": 0.3895,
"liquidAccumulation": 0.121,
"snowAccumulation": 0.2685,
"iceAccumulation": 0,
```

Dev:
```json
"time": 1733893200,
"summary": "Flurries",
"icon": "snow",
"dawnTime": 1733918296,
"sunriseTime": 1733920370,
"sunsetTime": 1733951995,
"duskTime": 1733954068,
"moonPhase": 0.35,
"precipIntensity": 0.1856,
"precipIntensityMax": 0.5563,
"precipIntensityMaxTime": 1733893200,
"precipProbability": 0.36,
"precipAccumulation": 0.44510000000000005,
"liquidAccumulation": 0.1766,
"snowAccumulation": 0.2685,
"iceAccumulation": 0,
```

The `snowAccumulation` is the same but the `liquidAccumulation` is different on dev. I checked the `sourceTimes` section to make sure there isn't any differences and the only difference is hrrr_subh is missing on dev but it shouldn't make a difference.

Live:
```json
"sourceTimes": {
  "hrrr_subh": "2024-12-05 15Z",
  "hrrr_0-18": "2024-12-05 14Z",
  "nbm": "2024-12-05 12Z",
  "nbm_fire": "2024-12-05 06Z",
  "hrrr_18-48": "2024-12-05 12Z",
  "gfs": "2024-12-05 06Z",
  "gefs": "2024-12-05 06Z"
},
```

Dev:
```json
"sourceTimes": {
  "hrrr_0-18": "2024-12-05 14Z",
  "nbm": "2024-12-05 12Z",
  "nbm_fire": "2024-12-05 06Z",
  "hrrr_18-48": "2024-12-05 12Z",
  "gfs": "2024-12-05 06Z",
  "gefs": "2024-12-05 06Z"
},
```

**Comment by alexander0042** [comment] 2024-12-05 17:07
No idea what's going on with subh, but that does help for accumulation! I also made a change to a filter than was in place- it used to round all values less than 0.01 to zero, but I realized that was catching some low precipitation moments, since over a day it adds up to a notable amount. I changed that threshold to 0.001, so I'm pretty sure that's what's happening here.

**Comment by cloneofghosts** [comment] 2024-12-05 17:18
> No idea what's going on with subh, but that does help for accumulation!

I've found that on the dev server hrrr_subh seems to come and go which might be happening when its updating to a new run? Elevation is 0 on the dev endpoint but it might be a dev endpoint thing.

**Comment by cloneofghosts** [comment] 2024-12-05 18:16
On days that have a rain/snow mix the `precipIntensity` and `precipIntensityMax` seem to go a bit haywire. As an example here's what it shows for Sunday:

```json
"time": 1733634000,
"summary": "Rain",
"icon": "rain",
"dawnTime": 1733658941,
"sunriseTime": 1733661006,
"sunsetTime": 1733692792,
"duskTime": 1733694857,
"moonPhase": 0.24,
"precipIntensity": 2.5345,
"precipIntensityMax": 8.683,
"precipIntensityMaxTime": 1733680800,
"precipProbability": 0.96,
"precipAccumulation": 6.0828,
"liquidAccumulation": 0.0762,
"snowAccumulation": 6.0066,
"iceAccumulation": 0,
```

As a separate note the API is predicting a lot more precipitation on Sunday than other sites. Other sites I've checked (accu and weather.com) are showing a bit of snow on Sunday and a bit of rain (if forecasted)

**Comment by alexander0042** [comment] 2024-12-05 18:34
This is the long-standing snow/rain issue that we keep running into, and why the separate snow/liquid amounts are so much nice. What's happening here is that there's rain for like 12 hours, so it uses the rain icon; however, there's 6 cm of snow during the day, and one hour when 0.868 cm of snow are forecast (high, but not at all crazy). So we end up with a type that's rain (because it's the most common) and an amount that makes more sense for snow. 

I'm unhappy with the options every time this comes up, but my current thinking is one of two options:

1. Maybe we set the type to "snow" if there is any snow. That would give the same numbers as what's shown here, but with snow instead of rain. This removes the risk of crazy high rainfall amounts, at the risk of underestimating things if there's a little snow forecast with a lot of rain. 
2. Calculate the snow/water ratio for intensity and accumulation based on the icon, not on their own. So in this case, because the icon is rain,  `precipAccumulation` would read 0.0762 cm + 0.06006 cm = 0.67686 cm. This also produces more reasonable numbers, but now underestimates things in the other direction (if there's a lot of snow with a little rain).

**Comment by cloneofghosts** [comment] 2024-12-05 19:33
Taking into account that the daily summaries run from 4am-4am there is slightly more rain hours than snow hours. Some feedback to your options:

1. This could lead to situations where its forecasted to rain for most of the day but in the late evening/overnight hours it changes to snow and the API would show the snow icon. I thought maybe a solution here would be to use a threshold but at that point you'd be better off using the most common type.
2. This is kinda similar to what the API is currently doing for intensities correct? This might make the most sense to do when the precipitation is mainly rain? Looking at the example I posted the highest intensity (when using the snow:liquid ratio) is 0.8683. Since the main precipitation is rain it's using the average 2.5345 mm/h intensity when calculating the summaries when in reality the precipitation isn't really that heavy.

My first thoughts on this was to leverage the mixed precipitation text that Dark Sky has in their translation library. The issue is that there is no `mixed` icon or precipitation type so would need to be added. Not ideal all things considered.

This isn't really a solution to this issue but what might help would be adding a half day forecast (as I suggested here: https://github.com/Pirate-Weather/pirateweather/issues/49). Taking Sunday as an example the "day" would likely show snow and the "night" would likely show rain. Doesn't really help those that are just showing an overall day icon but would still be useful.

**Comment by alexander0042** [comment] 2024-12-06 19:49
I've spent too much time thinking about this, since really, the answer is to add a "mixed" precipitation type for the daily results, but until we do that (breaking change), then we need a workable plan. 

What I've come up with is based on your "thresholds": comment, since I think there's potential there! I wrote out a bit of an algorithm for `precipType` that seems to be producing reasonable results:

1.   The logic here is trying to guess what the most "useful" type of precipitation would be, while avoiding strange results
2. First, if there is a ton of rain, that should show up even if there's a lot of snow "hours"
3. Then, since snow is 10x rain, the rain icon shouldn't appear is there is much snow, otherwise it looks like an unreasonable amount of rain. So snow greater than 5 mm takes priority over rain.
4. Finally, if there is much ice at all, that takes priority over rain or snow.

This gives a daily type, which is the starting point for the icon. I also edited the text/ icon generation code to pick an icon like this:
```
    # Find the largest percentage difference to determine the icon
    if pop>0.25 and ((rainPrep > rainIconThreshold) or (snowPrep > snowIconThreshold) or (icePrep > iceIconThreshold)):
        if precipType == 'rain':
            cIcon = "rain" # Fallback icon
        else:
            cIcon = precipType
```

Using 10 mm of snow, 1 mm of rain/ ice for daily thresholds, and 0.2 mm for all the hourly snow/  0.02 mm for the hourly rain threshold. The text (light, medium, heavy) is then based on the accumulation rates, depending on what type is selected. I also removed the "none" fallback, since that's been added to the main script.

I'm going to watch this approach over the weekend to see how it does, but it seems promising so far. One issue is that the daily text biased towards precipitation, since it's added even if very little is predicted. However, it's just a daily stopgap, and I think still better than the current implementation

**Comment by cloneofghosts** [comment] 2024-12-06 20:00
I'm seeing a new issue where the daily/hourly blocks are showing the possible precipitation text even when no precipitation is forecasted:

hourly:

```json
{
  "time": 1733511600,
  "summary": "Possible Flurries",
  "icon": "partly-cloudy-day",
  "precipIntensity": 0,
  "precipProbability": 0,
  "precipIntensityError": 0,
  "precipAccumulation": 0,
  "precipType": "snow",
  "temperature": -5.71,
  "apparentTemperature": -12.59,
  "dewPoint": -12.71,
  "humidity": 0.58,
  "pressure": 1017.6,
  "windSpeed": 18.72,
  "windGust": 29.52,
  "windBearing": 280,
  "cloudCover": 0.78,
  "uvIndex": 1.28,
  "visibility": 16.09,
  "ozone": 345.4
},
```

daily:
```json
{
  "time": 1733461200,
  "summary": "Possible Flurries",
  "icon": "partly-cloudy-day",
  "sunriseTime": 1733488088,
  "sunsetTime": 1733520004,
  "moonPhase": 0.17,
  "precipIntensity": 0,
  "precipIntensityMax": 0,
  "precipIntensityMaxTime": 1733472000,
  "precipProbability": 0,
  "precipAccumulation": 0,
  "precipType": "snow",
  "temperatureHigh": -5.46,
  "temperatureHighTime": 1733518800,
  "temperatureLow": -9.09,
  "temperatureLowTime": 1733569200,
  "apparentTemperatureHigh": -11.43,
  "apparentTemperatureHighTime": 1733518800,
  "apparentTemperatureLow": -13.61,
  "apparentTemperatureLowTime": 1733569200,
  "dewPoint": -11.31,
  "humidity": 0.71,
  "pressure": 1016.29,
  "windSpeed": 19.14,
  "windGust": 30.4,
  "windGustTime": 1733461200,
  "windBearing": 276.67,
  "cloudCover": 0.58,
  "uvIndex": 1.86,
  "uvIndexTime": 1733504400,
  "visibility": 16.09,
  "temperatureMin": -8.84,
  "temperatureMinTime": 1733486400,
  "temperatureMax": -5.46,
  "temperatureMaxTime": 1733461200,
  "apparentTemperatureMin": -16.56,
  "apparentTemperatureMinTime": 1733486400,
  "apparentTemperatureMax": -11.05,
  "apparentTemperatureMaxTime": 1733544000
},
```

If there is any precipitation then it works correctly.

**Comment by alexander0042** [comment] 2024-12-06 20:02
Missed a check, fixing now!

**Comment by alexander0042** [comment] 2024-12-06 20:06
Ok, live now and updated in the repo!

**Comment by cloneofghosts** [comment] 2024-12-06 20:13
Yup, this is fixed.

So basically in 2.6 a new `precipType` will be added for Mixed Precipitation and will show up if a day has multiple precipitation types forecasted? Could it also be applied to hourly as well since you have snow/rain/ice accumulation on hourly as well so if multiple are > 0 then show it or is that not how it works?

**Comment by cloneofghosts** [comment] 2024-12-06 22:17
> I'm going to watch this approach over the weekend to see how it does, but it seems promising so far. One issue is that the daily text biased towards precipitation, since it's added even if very little is predicted. However, it's just a daily stopgap, and I think still better than the current implementation

This might be making things too complicated and might be a bit confusing but maybe in cases where the icon doesn't show add the sky text to it. So it could say something like Mostly Cloudy and Possible Drizzle.

**Comment by cloneofghosts** [comment] 2024-12-07 17:10
> I'm going to watch this approach over the weekend to see how it does, but it seems promising so far. One issue is that the daily text biased towards precipitation, since it's added even if very little is predicted. However, it's just a daily stopgap, and I think still better than the current implementation

@alexander0042 I've noticed that the dev endpoint has been down for about 4-5 hours now (Internal Server Error). Before I would get the occasional Internal Server Error but it would work after a few retries.

**Comment by cloneofghosts** [comment] 2024-12-09 15:09
@alexander0042 Any ETA on when the dev site will be back up? It's been down all weekend.

**Comment by cloneofghosts** [comment] 2024-12-09 16:27
> Now, re the downtime, this is an issue, For some reason the JS2Py bridge seems to go unstable and hang every so often, but doesn't show any outward sign if what's the underlying problem... As a testing idea, I'm going to see how doable it would be to convert the translations repo to pure Python. It has so few js dependencies that I really think it ought to be doable (wit ChatGPT of course), and that would be a cleaner solution.

That's a bit annoying that the bridge seems to cause issues. Also the API endpoint is returning an Internal Server Error now.

**Comment by cloneofghosts** [comment] 2024-12-09 17:12
> Current instability is from a ton of timemachine requests coming simultaneously- I made a new deployment config which should help with things, but also going to add a per API key rate limit of 1 to 4/ per second (depending on the plan) to avoid this sort of issue

It's back up now. Let me know how it goes converting the Translations library to python but the dev endpoint seems to be back up (for now)

**Comment by alexander0042** [comment] 2024-12-09 17:49
Going great, so that's a win! English and French are working in my testing, and it's a simple additional script that does what translations.js used to do <https://chatgpt.com/share/67572c9e-647c-800d-b758-07081fd6da81>.

Here's a question- what's the best way to handle this from a Git standpoint? Would you rather I keep the translations repo and submit a PR that changes all the files over to Python, then set it as a submodule in pirate-weather-code so it gets cloned in? Or leave it as is and save the files directly to the 2.5.0 branch of code in a lib/lang folder?

**Comment by alexander0042** [comment] 2024-12-09 19:03
I agree- because it's forked off Dark Sky, I kind of want to keep the history there as well. What I'll do is add a link to it from the main repo as a [submodule](https://gist.github.com/gitaarik/8735255), which is important for self hosting, since it'll get downloaded at the same time

**Comment by cloneofghosts** [comment] 2024-12-10 16:12
@alexander0042 I thought for currently if `precipIntensity` is above 0.02 mm/h then it would show the icon and it wouldn't show the possible text. This is what I'm currently seeing on the dev endpoint at the moment:

```json
currently": {
  "time": 1733846940,
  "summary": "Possible Light Sleet",
  "icon": "cloudy",
  "nearestStormDistance": 216.31,
  "nearestStormBearing": 90,
  "precipIntensity": 0.217,
  "precipProbability": 0.11,
  "precipIntensityError": 0.04,
}
```

Live is showing the icon/summary as sleet. I assume because the probability is only 11% it's not showing the icon and adds the possible text?

**Comment by cloneofghosts** [comment] 2024-12-10 18:38
I'm guessing you're still working on porting the translations repo to python? Haven't seen a PR yet so I assume it's still in progress.

**Comment by cloneofghosts** [comment] 2024-12-10 20:12
I'm going to close this issue and create separate issues for the other items as this one is getting pretty long.

**Closed by cloneofghosts** 2024-12-10 20:12 UTC
Labels: enhancement

**Comment by cloneofghosts** [comment] 2024-12-10 20:20
I'm going to close this issue and create separate issues for the other items as this one is getting pretty long

@alexander0042 Just an FYI I created: https://github.com/Pirate-Weather/pirateweather/issues/385 and https://github.com/Pirate-Weather/translations/issues/24 to keep track of the two issues.
